### ISSUE TITLE
Bad argument: table expected, got nil

### ISSUE THREAD

**Issue by TheNathanSpace** [SquidDev-CC/CC-Images#2]
I'm trying to use this as outlined in your forum post [here](http://www.computercraft.info/forums2/index.php?/topic/19044-bitmap-images/). Whenever I do this, I get the error `ExampleUsage:18: bad argument: table expected, got nil`.

This is the line it fails on: `for Y, Values in pairs(Parser.Pixels) do`

You can see that the [code I'm using](https://pastebin.com/212Qwved) is identical to what you showed on the forum post.

The image I'm using can be found [here](https://raw.githubusercontent.com/TheKingElessar/CC-Programs/master/Freud-32.bmpF). I download it using `wget https://raw.githubusercontent.com/TheKingElessar/CC-Programs/master/Freud-32.bmp Freud.bmp`, then run `monitor right ExampleUsage Freud.bmp`.

I'm using your mod [CC: Tweaked](https://github.com/SquidDev-CC/CC-Tweaked).

Do you know what could be causing this?

**Comment by SquidDev** [comment]
Oh, that should be a lowercase `pixels` - `parser.pixels`. Sorry!

**Comment by TheNathanSpace** [comment]
Wow, thanks! I wasn't sure if you would reply or not. That help—it's now throwing a different error on the line `term.setBackgroundColour(col)`: `bad argument #1 (number expected, got table)`.

I tried to figure out what the problem is, but I don't have any Lua experience and can't even figure out where the `pixels` object is originating from in the API.

For reference, here's the entire block:
```
for y, values in pairs(Parser.pixels) do
    for x, col in pairs(values) do
        term.setCursorPos(x, y)
        term.setBackgroundColour(col)
        term.write(" ")
    end
end
```

Thanks for your help on this!

**Comment by SquidDev** [comment]
Sorry, it's been ~5 years since I worked on this (oh wow, I feel old), so taken me a while to work this all out! I _think_ it's sufficient to do this instead of the loop:

```lua
ImagesAPI.ImageHelpers.drawImage(Parser)
```

**Comment by TheNathanSpace** [comment]
That works great, thanks for your help! I appreciate it.
