### ISSUE TITLE
Bitmap Images API: Can't find a parser for depth 16

### ISSUE THREAD

**Issue by TBleader** [SquidDev-CC/CC-Images#4]
I don't know if this is still active or if you respond (you did in November but the project hasn't seen any activity really so no biggie if it's totally abandoned...) but I am having some trouble getting this to work. I have it downloaded and am trying to use it with an image but I get
`ImagesAPI:421: Can't find a parser for depth 16`

The code for the program I am trying to run below
    if not ImagesAPI then
        os.loadAPI(fs.combine(fs.getDir(shell.getRunningProgram()), "ImagesAPI"))
    end
     
    local args = {...}
    if #args < 2 then
        error("monProgram.lua <image> <monitor>")
    end
     
    monitor = peripheral.find(args[2])
     
    monitor.clear()
    monitor.setTextScale(0.5)
    monitor.setCursorPos(1,1)
     
    local Parser = ImagesAPI.ImageHelpers.parseFile(args[1])
     
    term.redirect(monitor)
    ImagesAPI.ImageHelpers.drawImage(Parser)
    term.redirect()
     
    print("\n")

I adapted it from the forum post and from a previous comment you made on a closed issue here. I am trying to draw the image to a monitor connected by a wired modem. To acquire the file onto the computer I have been using the following script

    local args = {...}
    if #args < 2 then
        error("filedownloader.lua <url> <filename>")
    end
    print("Downloading file...")
    local request, err = http.get(args[1], nil, true)
    if not request then error(err) end
    local file = fs.open(args[2], "wb")
    file.write(request.readAll())
    file.close()
    request.close()
    print("Saved file as"..args[2])

I am thinking maybe the issue is that the file isn't being imported correctly, or maybe I am just using this API wrong? Any help would be greatly appreciated!

**Comment by SquidDev** [comment]
> I don't know if this is still active

Yeah, it's not. Sorry!

Basically the issue is [bmp files support various pixel formats](https://en.wikipedia.org/wiki/BMP_file_format#Pixel_format), but we only support some of them (1, 4, 8, 24bits), and 16 isn't one of them! The easiest thing is to re-export your image in an alternative format.
